version: '3.1'
services:
  credit-service:
    container_name: moneta-credit-service
    build: ./
    ports:
      - "8091:8091"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
